[lua54]
no-default-features = true
features = "lua54,vendored,send,serde,macros,anyhow,userdata-wrappers"

[lua54_non_send]
no-default-features = true
features = "lua54,vendored,serde,macros,anyhow,userdata-wrappers"

[lua54_with_memory_limit]
no-default-features = true
features = "lua54,vendored,send,serde,macros,anyhow,userdata-wrappers"
rustflags = "--cfg force_memory_limit"

[lua51]
no-default-features = true
features = "lua51,vendored,send,serde,macros"

[lua51_with_memory_limit]
no-default-features = true
features = "lua51,vendored,send,serde,macros"
rustflags = "--cfg force_memory_limit"

[luau]
no-default-features = true
features = "luau,send,serde,macros"

[luau_with_memory_limit]
no-default-features = true
features = "luau,send,serde,macros"
rustflags = "--cfg force_memory_limit"
