name: CI
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable]
        lua: [luau, luau-jit, luau-vector4]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@main
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2
      - name: Build ${{ matrix.lua }} vendored
        run: |
          cargo build --features "${{ matrix.lua }},vendored" --no-default-features
          cargo build --features "${{ matrix.lua }},vendored,serde" --no-default-features
          cargo build --features "${{ matrix.lua }},vendored,serde,send" --no-default-features
        shell: bash
      - name: Build ${{ matrix.lua }} pkg-config
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends liblua5.4-dev liblua5.3-dev liblua5.2-dev liblua5.1-0-dev libluajit-5.1-dev
          cargo build --features "${{ matrix.lua }}" --no-default-features

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable, nightly]
        lua: [luau, luau-jit, luau-vector4]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@main
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2
      - name: Run ${{ matrix.lua }} tests
        run: |
          cargo test --no-default-features --features "${{ matrix.lua }},vendored"
          cargo test --no-default-features --features "${{ matrix.lua }},vendored,serde"
          cargo test --no-default-features --features "${{ matrix.lua }},vendored,serde,send"
        shell: bash

  test_with_sanitizer:
    name: Test with address sanitizer
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [nightly]
        lua: [luau, luau-jit, luau-vector4]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@main
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2
      - name: Run ${{ matrix.lua }} tests with address sanitizer
        run: |
          cargo test --no-default-features --tests --features "${{ matrix.lua }},vendored,serde" --target x86_64-unknown-linux-gnu -- --skip test_too_many_recursions
          cargo test --no-default-features --tests --features "${{ matrix.lua }},vendored,serde,send" --target x86_64-unknown-linux-gnu -- --skip test_too_many_recursions
        shell: bash
        env:
          RUSTFLAGS: -Z sanitizer=address

  test_with_memory_limit:
    name: Test with memory limit
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [nightly]
        lua: [luau, luau-jit, luau-vector4]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@main
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2
      - name: Run ${{ matrix.lua }} tests with forced memory limit
        run: |
          cargo test --no-default-features --tests --features "${{ matrix.lua }},vendored,send,serde"
        shell: bash
        env:
          RUSTFLAGS: --cfg=force_memory_limit

  test_wasm32_emscripten:
    name: Test on wasm32-unknown-emscripten
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lua: [luau]
    steps:
      - uses: actions/checkout@main
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: wasm32-unknown-emscripten
      - name: Install Emscripten
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends emscripten
      - name: Run ${{ matrix.lua }} tests
        run: |
          cargo test --tests --features "${{ matrix.lua }},vendored" --no-default-features
          cargo test --tests --features "${{ matrix.lua }},vendored,serde" --no-default-features

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lua: [luau, luau-jit, luau-vector4]
    steps:
      - uses: actions/checkout@main
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: clippy
      - uses: giraffate/clippy-action@v1
        with:
          reporter: 'github-pr-review'
          clippy_flags: --features "${{ matrix.lua }},vendored,send,serde"
